# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdOutside = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdOutside.setGeometry(QtCore.QRect(600, 10, 64, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcdOutside.setFont(font)
        self.lcdOutside.setAutoFillBackground(False)
        self.lcdOutside.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Sans Serif\";\n"
"")
        self.lcdOutside.setSmallDecimalPoint(True)
        self.lcdOutside.setDigitCount(4)
        self.lcdOutside.setProperty("intValue", 62)
        self.lcdOutside.setObjectName("lcdOutside")
        self.pbOutside = QtWidgets.QProgressBar(self.centralwidget)
        self.pbOutside.setGeometry(QtCore.QRect(110, 10, 481, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbOutside.setFont(font)
        self.pbOutside.setMinimum(-5)
        self.pbOutside.setMaximum(120)
        self.pbOutside.setProperty("value", 24)
        self.pbOutside.setObjectName("pbOutside")
        self.pbDog = QtWidgets.QProgressBar(self.centralwidget)
        self.pbDog.setGeometry(QtCore.QRect(110, 40, 481, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbDog.setFont(font)
        self.pbDog.setMinimum(-5)
        self.pbDog.setMaximum(120)
        self.pbDog.setProperty("value", 24)
        self.pbDog.setObjectName("pbDog")
        self.pbGarage = QtWidgets.QProgressBar(self.centralwidget)
        self.pbGarage.setGeometry(QtCore.QRect(110, 70, 481, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbGarage.setFont(font)
        self.pbGarage.setMinimum(-5)
        self.pbGarage.setMaximum(120)
        self.pbGarage.setProperty("value", 24)
        self.pbGarage.setObjectName("pbGarage")
        self.lcdDog = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdDog.setGeometry(QtCore.QRect(600, 40, 64, 23))
        self.lcdDog.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.lcdDog.setSmallDecimalPoint(True)
        self.lcdDog.setDigitCount(4)
        self.lcdDog.setObjectName("lcdDog")
        self.lcdGarage = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdGarage.setGeometry(QtCore.QRect(600, 70, 64, 23))
        self.lcdGarage.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdGarage.setSmallDecimalPoint(True)
        self.lcdGarage.setDigitCount(4)
        self.lcdGarage.setObjectName("lcdGarage")
        self.lblOutside = QtWidgets.QLabel(self.centralwidget)
        self.lblOutside.setGeometry(QtCore.QRect(20, 10, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblOutside.setFont(font)
        self.lblOutside.setTextFormat(QtCore.Qt.PlainText)
        self.lblOutside.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOutside.setObjectName("lblOutside")
        self.lblDog = QtWidgets.QLabel(self.centralwidget)
        self.lblDog.setGeometry(QtCore.QRect(10, 40, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblDog.setFont(font)
        self.lblDog.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDog.setObjectName("lblDog")
        self.lblGarage = QtWidgets.QLabel(self.centralwidget)
        self.lblGarage.setGeometry(QtCore.QRect(20, 70, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblGarage.setFont(font)
        self.lblGarage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGarage.setObjectName("lblGarage")
        self.btnFanGarage = QtWidgets.QPushButton(self.centralwidget)
        self.btnFanGarage.setGeometry(QtCore.QRect(520, 340, 100, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnFanGarage.setFont(font)
        self.btnFanGarage.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btnFanGarage.setObjectName("btnFanGarage")
        self.btnFanDog = QtWidgets.QPushButton(self.centralwidget)
        self.btnFanDog.setGeometry(QtCore.QRect(520, 160, 100, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnFanDog.setFont(font)
        self.btnFanDog.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btnFanDog.setObjectName("btnFanDog")
        self.btnHeatDog = QtWidgets.QPushButton(self.centralwidget)
        self.btnHeatDog.setGeometry(QtCore.QRect(520, 250, 100, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnHeatDog.setFont(font)
        self.btnHeatDog.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btnHeatDog.setObjectName("btnHeatDog")
        self.lbl_Dog_Fan_State = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Dog_Fan_State.setGeometry(QtCore.QRect(640, 160, 150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.lbl_Dog_Fan_State.setFont(font)
        self.lbl_Dog_Fan_State.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 12pt \"Arial Black\";")
        self.lbl_Dog_Fan_State.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_Dog_Fan_State.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_Dog_Fan_State.setLineWidth(2)
        self.lbl_Dog_Fan_State.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Dog_Fan_State.setObjectName("lbl_Dog_Fan_State")
        self.lbl_Dog_Heat_State = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Dog_Heat_State.setGeometry(QtCore.QRect(640, 250, 150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.lbl_Dog_Heat_State.setFont(font)
        self.lbl_Dog_Heat_State.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_Dog_Heat_State.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_Dog_Heat_State.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_Dog_Heat_State.setLineWidth(2)
        self.lbl_Dog_Heat_State.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Dog_Heat_State.setObjectName("lbl_Dog_Heat_State")
        self.lbl_Garage_Fan_State = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Garage_Fan_State.setGeometry(QtCore.QRect(640, 340, 150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.lbl_Garage_Fan_State.setFont(font)
        self.lbl_Garage_Fan_State.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 12pt \"Arial Black\";")
        self.lbl_Garage_Fan_State.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_Garage_Fan_State.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_Garage_Fan_State.setLineWidth(2)
        self.lbl_Garage_Fan_State.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Garage_Fan_State.setObjectName("lbl_Garage_Fan_State")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 390, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblBroker_status = QtWidgets.QLabel(self.centralwidget)
        self.lblBroker_status.setGeometry(QtCore.QRect(10, 340, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBroker_status.setFont(font)
        self.lblBroker_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblBroker_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblBroker_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBroker_status.setObjectName("lblBroker_status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pbGarage.valueChanged['int'].connect(self.lcdGarage.display)
        self.pbDog.valueChanged['int'].connect(self.lcdDog.display)
        self.pbOutside.valueChanged['int'].connect(self.lcdOutside.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbOutside.setFormat(_translate("MainWindow", "%v"))
        self.pbDog.setFormat(_translate("MainWindow", "%v"))
        self.pbGarage.setFormat(_translate("MainWindow", "%v"))
        self.lblOutside.setText(_translate("MainWindow", "Outside"))
        self.lblDog.setText(_translate("MainWindow", "Dog House"))
        self.lblGarage.setText(_translate("MainWindow", "Garage"))
        self.btnFanGarage.setText(_translate("MainWindow", "Garage\n"
" Fan\n"
"Disabled"))
        self.btnFanDog.setText(_translate("MainWindow", "Dog House\n"
"Fan\n"
"Disabled"))
        self.btnHeatDog.setText(_translate("MainWindow", "Dog House\n"
"Heat\n"
"Disabled"))
        self.lbl_Dog_Fan_State.setText(_translate("MainWindow", "Dog Fan\n"
" Off"))
        self.lbl_Dog_Heat_State.setText(_translate("MainWindow", "Dog Heat\n"
"Off"))
        self.lbl_Garage_Fan_State.setText(_translate("MainWindow", "Garage Fan\n"
"Off"))
        self.label.setText(_translate("MainWindow", "Sensor"))
        self.lblBroker_status.setText(_translate("MainWindow", "Broker"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
